export const FETCH_APPS_PENDING = 'FETCH_APPS_PENDING';
export const FETCH_APPS_FULFILLED = 'FETCH_APPS_FULFILLED';
export const FETCH_APPS_REJECTED = 'FETCH_APPS_REJECTED';
export const CHANGE_APPS = 'CHANGE_APPS';